"""first

Revision ID: 2300d7d99ef0
Revises: be76fdd0f1d1
Create Date: 2025-08-22 21:27:42.781097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2300d7d99ef0'
down_revision: Union[str, Sequence[str], None] = 'be76fdd0f1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user_detail', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'last_name')
    op.drop_column('user_detail', 'first_name')
    # ### end Alembic commands ###
