"""first one

Revision ID: 4f11738c2335
Revises: 5e9cb9f41dff
Create Date: 2025-08-24 03:39:59.741436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f11738c2335'
down_revision: Union[str, Sequence[str], None] = '5e9cb9f41dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('valid_until', sa.DateTime()))
    op.drop_column('service', 'today_notification_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('today_notification_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('service', 'valid_until')
    # ### end Alembic commands ###
