"""create tables

Revision ID: c91481a99cc4
Revises: dc11ad3bf712
Create Date: 2025-08-23 18:56:41.834771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91481a99cc4'
down_revision: Union[str, Sequence[str], None] = 'dc11ad3bf712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service', ['bill_id'])
    op.add_column('user_service', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('user_service', sa.Column('bill_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('user_service_service_id_fkey'), 'user_service', type_='foreignkey')
    op.drop_constraint(op.f('user_service_user_id_fkey'), 'user_service', type_='foreignkey')
    op.create_foreign_key(None, 'user_service', 'user_detail', ['chat_id'], ['chat_id'])
    op.create_foreign_key(None, 'user_service', 'service', ['bill_id'], ['bill_id'])
    op.drop_column('user_service', 'user_id')
    op.drop_column('user_service', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_service', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_service', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_service', type_='foreignkey')
    op.drop_constraint(None, 'user_service', type_='foreignkey')
    op.create_foreign_key(op.f('user_service_user_id_fkey'), 'user_service', 'user_detail', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('user_service_service_id_fkey'), 'user_service', 'service', ['service_id'], ['id'])
    op.drop_column('user_service', 'bill_id')
    op.drop_column('user_service', 'chat_id')
    op.drop_constraint(None, 'service', type_='unique')
    # ### end Alembic commands ###
